var block_scroll;var last_termino;var block_click;var last_keyup;var log_id;function delay(callback,ms){var timer=0;return function(){var context=this,args=arguments;clearTimeout(timer);timer=setTimeout(function(){callback.apply(context,args);},ms||0);};}
function initBuscador(){$('#buscador_close_search').click(function(e){e.preventDefault();closeBuscador();});$(document).keyup(function(e){if(e.key==="Escape"||e.key==="Esc")
closeBuscador();});$('#buscador_resultados_content').bind('scroll',function(){if($(this)[0].scrollHeight-$(this).scrollTop()<=$(this).outerHeight()&&!block_scroll){block_scroll=true;getSearchItems(false);}});$(".buscador-section .search-form .search-input").on('input',delay(function(e){var value=$(this).val();if(last_termino!=value){searchAutocomplete();}},400));$(".buscador-section .search-form .search-input").on('keypress',function(e){var value=$(this).val();if(e.which==13&&last_termino!=value&&value.length>1){printItems(value);}});$(".buscador-section #buscar_btn").on('click',function(e){var value=$('#buscador_search_input').val();if(last_termino!=value&&value.length>1){printItems(value);}});$(".buscador-section #search_options").on('click','a',function(e){e.preventDefault();searchAutocompleteClick($(this).find('li').html());});$('#buscador_resultados_content').on('click','.articulo a',function(e){e.preventDefault();var idx=$(this).closest('.articulo').index();var idg=$(this).closest('.group-content').data('id');if(!block_click){block_click=true;sendStatsLog('click',false,$(this).data('href'),idx,idg);}});}
function closeBuscador(){$('#buscador_search_input').val('');last_termino=false;$('#buscador_search_input').focusout();$('body').removeClass('noscroll');$('#buscador_resultados_content').scrollTop(0);$('#buscador_resultados').addClass('hide');$('#buscador_resultados_content').html('');closeAutocomplete();}
function printItems(termino){last_keyup=Date.now();last_termino=termino;block_scroll=false;closeAutocomplete();$('#buscador_resultados_content').html('');$('.buscador-section .search-form .actual-page').val('1');if(!termino)
$('#buscador_resultados .header .title').html('');getSearchItems(true);}
function getSearchItems(send_log){var termino=$('#buscador_search_input').val();var pagina=Number($('.buscador-section .search-form .actual-page').val());if(termino){$.ajax({type:"POST",url:js_domain+"home/search/desktop/",data:{pagina:pagina,termino:termino},dataType:"json",success:function(data)
{var div=$('#buscador_resultados');if(pagina==1)
div.find('.header').find('.title').html(data.msg);if(data.status=='ok'){$('body').addClass('noscroll');div.find('.content').append(data.html);div.removeClass('hide');$('.buscador-section .search-form .actual-page').val(pagina+1);new LazyLoad({elements_selector:".lazy"});block_scroll=false;if(pagina==1&&send_log){setTimeout(function(){if(Date.now()-last_keyup>800){sendStatsLog('search',data.total,false,false,false);}},800);}}}});}}
function sendStatsLog(type,total,redirect,pos,grupo){var termino=$('#buscador_search_input').val();if(termino){$.ajax({type:"POST",url:js_domain+"home/search_log/desktop/",data:{termino:termino,total:total,type:type,log_id:log_id,pos:pos,grupo:grupo},dataType:"json",success:function(data)
{if(data.status=='ok'){if(type=='search'){log_id=data.log_id;}}},complete:function(){if(redirect!==false){window.location.href=redirect;}}});}}
function searchAutocomplete(){var termino=$('#buscador_search_input').val();if(termino){$.ajax({type:"POST",url:js_domain+"home/search_autocomplete/",data:{termino:termino},dataType:"json",success:function(data)
{if(data.status=='ok'){$('.buscador-section .search-suggestions').addClass('visible');$("#search_options ul a").attr('data-find','n');for(var element in data.data){var elem=$("#search_options ul a[data-id='"+data.data[element]+"']");if(elem.length==0)
$('#search_options ul').append('<a data-find="s" href="#" data-id="'+data.data[element]+'"><li>'+data.data[element]+'</li></a>');else
elem.attr('data-find','s');}
$("#search_options ul a[data-find='n']").remove();}else{closeAutocomplete();}}});}}
function searchAutocompleteClick(value){$('#buscador_search_input').val(value);var e=jQuery.Event("keypress");e.which=13;e.keyCode=13;$("#buscador_search_input").trigger(e);}
function closeAutocomplete(){$('.buscador-section .search-suggestions').removeClass('visible');$('#search_options ul').empty();}
$(document).ready(function(){block_scroll=false;block_click=false;last_termino='';log_id=0;initBuscador();});